

use mydb;

CREATE TABLE IF NOT EXISTS goods(
goods_id  BIGINT UNSIGNED NOT NULL UNIQUE ,
tp INT UNSIGNED NOT NULL DEFAULT 0, -- 类型
name VARCHAR(128) NOT NULL,
description VARCHAR(1024) NOT NULL,
price DOUBLE(16,2) NOT NULL,
update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY(goods_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

