
use mydb;

CREATE TABLE IF NOT EXISTS orders(
order_id VARCHAR(255) NOT NULL ,
user_id BIGINT UNSIGNED NOT NULL,
goods_id BIGINT UNSIGNED NOT NULL,
goods_price DOUBLE(16,2) NOT NULL,
goods_num INT UNSIGNED NOT NULL,
cost DOUBLE(16,2) NOT NULL,
create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ,
stat INT NOT NULL,
PRIMARY KEY(order_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;


